version: '3.8'
name: docker-training

services:
  app:
    container_name: my-app
    image: docker-training-my-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildversion: 1
    ports:
      - 3000:3000
    networks:
      - docker-training-network
    volumes:
      - ./logs:/app/logs

networks:
  docker-training-network:

